node {
    stage 'Building image'
    git 'https://github.com/ishatiwari26/SpringBootJAPI-Jenkins-Docker' // checks out Dockerfile
    def myEnv = docker.build 'cqueiroz:snapshot'
    myEnv.inside {
        sh 'mvn clean package'
    }
}